### PR TITLE
Support generic array in constructor input

### PR DESCRIPTION
**Pull request by satyambnsal**
Relevant issue: #41 

**Changes Summary**
Support Generic array as input in contract methods and constructor call.

### CODE REVIEW

**Comment by varex83** [comment]
Satyam, can you make it work not only for constructors?

**Comment by satyambnsal** [comment]
> Satyam, can you make it work not only for constructors?

Yes, I'm going to add support for method as well.

**Comment by satyambnsal** [comment]
Following changes can be tested with Voting contract 
https://gist.github.com/satyambnsal/5e8165392e21b3d50d8da1ffad5b906c

Here constructor takes candidate name array and method `getCandidates` take array of candidate index (ex. `[0,1]`)

**Comment by varex83** [comment]
Not working on my side, after deploying with some contructor args I'm getting this: 
image
image

**Review by varex83 — CHANGES_REQUESTED** [review]
we need to fix the issue with plugin crashing

**Comment by satyambnsal** [comment]
@varex83 What constructor arguments did you use ?

**Comment by satyambnsal** [comment]
> we need to fix the issue with plugin crashing

Thank you @varex83 for catching this. its fixed now.  This was happening due to initial inputs array being set to empty array instead of based on element inputs array length.

**Review by varex83 — APPROVED** [review]
Can confirm that it is working now. GTG

**Review by varex83 — APPROVED** [review]
Can confirm that it is working now. GTG

**Pull request merged**
