### PR TITLE
Environment Refactor changes

### PR DESCRIPTION
**Pull request by satyambnsal**
**Changes Summary**

1. Current Env component to show current selected environment
2. UI style changes

### CODE REVIEW

**Review by varex83 — CHANGES_REQUESTED** [review]
Requested changes in the Slack

**Review by varex83 — CHANGES_REQUESTED** [review]
1. On low-width layout is broken for the account selection
2. The same for Manual Account
3. "Settings" tab goes out of borders

**Comment by satyambnsal** [comment]
> 1. On low-width layout is broken for the account selection
> 2. The same for Manual Account
> 3. "Settings" tab goes out of borders

Thanks @varex83 for the feedback.

**Review by varex83 — APPROVED** [review]
Looks very good now!

**Pull request merged**
